name = "Havoc Realms S6"
author = "minecraftbossdj, minecraftbossdj, and minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e57ab80bc8f7eba75ac864e13dd94c7f22d3c0238f6784522ff707f01c91bff4"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
